services:
  composer:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.composer
    container_name: yii_composer
    volumes:
      - .:/app
    command: install --ignore-platform-reqs
    working_dir: /app
    user: $PACKAGER

  php-cli:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.php-cli
    links:
      - composer
    user: $PACKAGER
    volumes:
      - .:/app
    working_dir: /app

  nginx:
    container_name: yii_web
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    volumes:
      - .:/var/www
      - ./logs/docker/nginx:/var/log/nginx
    working_dir: /var/www
    ports:
      - "8080:80"
    depends_on:
      - mysql
    links:
      - composer


  mysql:
    container_name: yii_db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret

  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret
