services:
  composer:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.composer
    container_name: yii_composer
    volumes:
      - .:/app
    command: install --ignore-platform-reqs
    working_dir: /app
    user: $PACKAGER

  php-cli:
    container_name: yii_cli
    build:
      context: .
      dockerfile: ./docker/Dockerfile.php-cli
    links:
      - composer
    user: $PACKAGER
    env_file:
      - .env
      - .env.local
    volumes:
      - .:/app
    depends_on:
      - mysql
    working_dir: /app

  php-fpm:
    container_name: yii_fpm
    build:
      context: .
      dockerfile: ./docker/Dockerfile.php-fpm
    user: $PACKAGER
    env_file:
      - .env
      - .env.local
    volumes:
      - .:/var/www/
    working_dir: /var/www/
    depends_on:
      - mysql
    links:
      - composer

  nginx:
    container_name: yii_web
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    volumes:
      - .:/var/www
      - ./logs/docker/nginx:/var/log/nginx
    working_dir: /var/www
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    links:
      - composer

  mysql:
    container_name: yii_db
    image: mysql:8.4
    env_file:
      - .env
      - .env.local
    ports:
      - "13306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
